### ISSUE TITLE
Error: Cannot find module './server'

### ISSUE THREAD

**Issue by mcvince79** [simojenki/bonob#162]
Hello,
I just installed navidrome on a nas asustor via portainer. It works fine. Bonob is also installed on portainer. It works but in the logs I always have the following error : 

node:internal/modules/cjs/loader:1029
      
  throw err;
  ^
Error: Cannot find module './server'
Require stack:
- /bonob/src/app.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/bonob/src/app.js:32:34)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/bonob/src/app.js' ]

Please help me

**Comment by simojenki** [comment]
So it works, but you see that error?

How often does the error happen?

**Comment by mcvince79** [comment]
No it doesn't work at all! It's just installed.

**Comment by simojenki** [comment]
Which docker image/version are you using?

**Comment by mcvince79** [comment]
app docker asustor

**Comment by simojenki** [comment]
I don't know what an asustor is, nor what instruction set it uses. Amd64? Arm??

**Comment by mcvince79** [comment]
Arm v7 or v8

**Comment by mcvince79** [comment]
Please help me. Navidrome is ok. Bonob log same error :

Error: Cannot find module './server'
Require stack:
- /bonob/src/app.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/bonob/src/app.js:32:34)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/bonob/src/app.js' ]
}

**Comment by mcvince79** [comment]
bonob is running. I can't connect to address 4534. Still the same error.

Error: Cannot find module './server'
Require stack:

/bonob/src/app.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
at Function.Module._load (node:internal/modules/cjs/loader:871:27)
at Module.require (node:internal/modules/cjs/loader:1098:19)
at require (node:internal/modules/cjs/helpers:108:18)
at Object. (/bonob/src/app.js:32:34)
at Module._compile (node:internal/modules/cjs/loader:1196:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
at Module.load (node:internal/modules/cjs/loader:1074:32)
at Function.Module._load (node:internal/modules/cjs/loader:909:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
code: 'MODULE_NOT_FOUND',
requireStack: [ '/bonob/src/app.js' ]

Please help me

**Comment by mcvince79** [comment]
Nobody ?

**Comment by simojenki** [comment]
Have you tried running this on a different machine?  Plenty of people use this project without reporting this issue, so perhaps there is something in your setup that is causing it?

**Comment by mcvince79** [comment]
Hello,

I'm getting to the point. Another mistake. The bonob service is well recognized in the sonos app. But I can't connect. Always the same message:

check your network connection. A problem occurred during startup. Please check your network connection, then try again.

**Comment by mcvince79** [comment]
Hello,

Please help

**Comment by simojenki** [comment]
This may because you have not set BNB_URL correctly.  It must be an address that is accessible by the Sonos devices

**Comment by mcvince79** [comment]
I've got it! Last question: what environment variable should I create so that the service never stops? I'm using docker desktop in windows 11. Thanks again for everything.

**Comment by mcvince79** [comment]
Because when I turn off my computer, I have to recreate the container every time.

**Comment by mcvince79** [comment]
In docker desktop, you can only create a container and nothing else.

**Comment by simojenki** [comment]
That's a windows/docker desktop thing, you need to work out how to get windows to start docker on boot. I'm sure it will be possible, however I don't use windows so how exactly I'm not sure.
